scrape_configs:
  - job_name: 'target-1'
    scrape_interval: 15s
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:8881']
        labels:
          group: 'app-group'

  - job_name: 'target-2'
    scrape_interval: 15s
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:8882']
        labels:
          group: 'app-group'

  - job_name: 'tomcat-exporter'
    scrape_interval: 15s
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:8686']
        labels:
          group: 'infra'
  
  # - job_name: 'another-jmx-exporter'
  #   scrape_interval: 15s
  #   metrics_path: /metrics
  #   static_configs:
  #     - targets: ['host.docker.internal:8888']
  #       labels:
  #         group: 'infra'
