{
 "title": "Tomcat dashboard",
 "description": "Tomcat dashboard using metrics from prometheus JMX exporter, with drill down per job > instance",
 "tags": [ "Tomcat8" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": "tomcat-exporter" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(jvm_info{job=\"$job\"}, instance)"
   },
   {
    "name": "protocol",
    "label": "Protocol",
    "query": "label_values(tomcat_bytesreceived_total{job=\"$job\", instance=~\"$instance\"}, protocol)"
   }
  ]
 },
 "panels": [
  {
   "title": "Server info",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "expr": "tomcat_serverinfo{job=\"$job\", instance=\"$instance\"}"
    }
   ]
  },
  { "title": "Protocol [$protocol]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }, "repeat": "protocol" },
  {
   "title": "Max threads",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 2, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "tomcat_threadpool_maxthreads{job=\"$job\", instance=\"$instance\", protocol=\"$protocol\"}"
    }
   ]
  },
  {
   "title": "Min spare threads",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "tomcat_threadpool_minsparethreads{job=\"$job\", instance=\"$instance\", protocol=\"$protocol\"}"
    }
   ]
  },
  {
   "title": "Accept count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "tomcat_threadpool_acceptcount{job=\"$job\", instance=\"$instance\", protocol=\"$protocol\"}"
    }
   ]
  },
  {
   "title": "Acceptor thread count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "tomcat_threadpool_acceptorthreadcount{job=\"$job\", instance=\"$instance\", protocol=\"$protocol\"}"
    }
   ]
  },
  {
   "title": "Poller thread count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 18, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "tomcat_threadpool_pollerthreadcount{job=\"$job\", instance=\"$instance\", protocol=\"$protocol\"}"
    }
   ]
  },
  {
   "title": "Traffic send/recv",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "increase(tomcat_bytesreceived_total{job=\"$job\", instance=\"$instance\", protocol=\"$protocol\"}[$__interval])",
     "legendFormat": "Received {{protocol}}[{{port}}]"
    },
    {
     "expr": "increase(tomcat_bytessent_total{job=\"$job\", instance=\"$instance\", protocol=\"$protocol\"}[$__interval])",
     "legendFormat": "Sent {{protocol}}[{{port}}]"
    }
   ]
  },
  {
   "title": "Request  count / error count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(tomcat_requestcount_total{job=\"$job\", instance=\"$instance\", protocol=\"$protocol\"}[$__interval])",
     "legendFormat": "Request {{protocol}}[{{port}}]"
    },
    {
     "expr": "increase(tomcat_errorcount_total{job=\"$job\", instance=\"$instance\", protocol=\"$protocol\"}[$__interval])",
     "legendFormat": "Error {{protocol}}[{{port}}]"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tomcat_threadpool_currentthreadcount{job=\"$job\", instance=\"$instance\", protocol=\"$protocol\"}",
     "legendFormat": "current {{protocol}}[{{port}}]"
    },
    {
     "expr": "tomcat_threadpool_currentthreadsbusy{job=\"$job\", instance=\"$instance\", protocol=\"$protocol\"}",
     "legendFormat": "current busy  {{protocol}}[{{port}}]"
    },
    {
     "expr": "tomcat_threadpool_connectioncount{job=\"$job\", instance=\"$instance\", protocol=\"$protocol\"}",
     "legendFormat": "connection  {{protocol}}[{{port}}]"
    },
    {
     "expr": "tomcat_threadpool_keepalivecount{job=\"$job\", instance=\"$instance\", protocol=\"$protocol\"}",
     "legendFormat": "keep alive  {{protocol}}[{{port}}]"
    }
   ]
  },
  { "title": "Servlet stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Session count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(tomcat_session_sessioncounter_total{job=\"$job\", instance=\"$instance\"}[$__interval])) by (instance)",
     "legendFormat": "New"
    },
    {
     "expr": "sum(increase(tomcat_session_expiredsessions_total{job=\"$job\", instance=\"$instance\"}[$__interval])) by (instance)",
     "legendFormat": "Expired"
    },
    {
     "expr": "sum(increase(tomcat_session_rejectedsessions_total{job=\"$job\", instance=\"$instance\"}[$__interval])) by (instance)",
     "legendFormat": "Rejected"
    }
   ]
  },
  {
   "title": "Session current count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 28 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(tomcat_session_sessioncounter_total{job=\"$job\", instance=\"$instance\"} - tomcat_session_expiredsessions_total)"
    }
   ]
  },
  {
   "title": "Session total created",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 31 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(tomcat_session_sessioncounter_total{job=\"$job\", instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Session total expired",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 34 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(tomcat_session_expiredsessions_total{job=\"$job\", instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Top 5 servlet request count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, increase(tomcat_servlet_requestcount_total{job=\"$job\", instance=\"$instance\"}[$__interval]))",
     "legendFormat": "module={{module}} servlet={{servlet}}"
    }
   ]
  },
  {
   "title": "Top 5 servlet error count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, increase(tomcat_servlet_errorcount_total{job=\"$job\", instance=\"$instance\"}[$__interval]))",
     "legendFormat": "module={{module}} servlet={{servlet}}"
    }
   ]
  },
  {
   "title": "Top 5 servlets average processing time per request",
   "type": "graph",
   "description": "Top 4 servlets average processing time per request in last 5 minutes",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "topk(5, increase(tomcat_servlet_processingtime_total{job=\"$job\", instance=\"$instance\"}[$__interval]) / increase(tomcat_servlet_requestcount_total{job=\"$job\", instance=\"$instance\"}[$__interval]))",
     "legendFormat": "module {{module}} servlet {{servlet}}"
    }
   ]
  }
 ]
}